version: 2
jobs:
  build:
    docker:
      - image: fischerscode/flutter:stable

    branches:
      only: master

    steps:
      - checkout

      - run:
          name: Run Flutter doctor
          command: cd core && flutter doctor

      - run:
          name: Run the application tests
          command: cd core && flutter test --converage

      - store_artifacts:
          path: core/coverage/lcov.info