version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  check:
    docker:
      - image: fischerscode/flutter:stable
    steps:
      - checkout
      - run:
          name: Run Flutter doctor
          command: |
            cd core
            flutter doctor
      - run:
          name: Install junitreport
          command: |
            cd core
            flutter pub global activate junitreport
      - run:
          name: Update PATH
          command: |
            echo 'export PATH=$PATH:$HOME/.pub-cache/bin' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Run the application tests
          command: |
            cd core
            flutter test --coverage
      - run:
          name: Generate XML Report
          command: |
            cd core
            mkdir test_result
            flutter test --machine | tojunit > test_result/TEST-Result.xml
      - store_test_results:
          path: core/test_result
      - store_artifacts:
          path: core/coverage/lcov.info
      - codecov/upload:
          file: core/coverage/lcov.info
          flags: unittests

  publish:
    docker:
      - image: fischerscode/flutter:stable
    steps:
      - checkout
      - run:
          name: Create credentials
          command: ls $HOME/flutter-sdk
      - run:
          name: Validate publish
          command: cd core && flutter packages pub publish --dry-run
      - run:
          name: Publish
          command: cd core && flutter packages pub publish --force
workflows:
  version: 2
  build:
    jobs:
      - check
      - publish:
          requires:
            - check
          filters:
            branches:
              only:
                - /^release\/.*$/