version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: fischerscode/flutter:stable
    steps:
      - checkout
      - run:
          name: Run Flutter doctor
          command: cd core && flutter doctor
  check:
    docker:
      - image: fischerscode/flutter:stable
    steps:
      - checkout
      - run:
          name: Install junitreport
          command: cd core && flutter pub global activate junitreport
      - run:
          name: Run the application tests
          command: cd core && flutter test --coverage --reporter json > test_result.json
      - run:
          name: Generate XML Report
          command: cd core && flutter pub global run junitreport:tojunit --input test_result.json --output TEST-Result.xml
      - store_test_results:
          path: core/TEST-Result.xml
      - store_artifacts:
          path: core/coverage/lcov.info
      - codecov/upload:
          file: core/coverage/lcov.info

  publish:
    docker:
      - image: fischerscode/flutter:stable
    steps:
      - checkout
      - run:
          name: Validate publish
          command: cd core && flutter packages pub publish --dry-run
      - run:
          name: Publish
          command: cd core && flutter packages pub publish --force
workflows:
  version: 2
  build:
    jobs:
      - build
      - check:
          filters:
            branches:
              only:
                - /^feature\/.*$/
      - publish:
          requires:
            - check
          filters:
            branches:
              only:
                - /^release\/.*$/